export const GET_SLOTS = 'GET_SLOTS';
export const SLOTS_LOADING = 'SLOTS_LOADING';
export const SLOTS_FAIL = 'SLOTS_FAIL';

export const GET_BOOKINGS = 'GET_BOOKINGS';
export const BOOKINGS_LOADING = 'BOOKINGS_LOADING';
export const BOOKINGS_FAIL = 'BOOKINGS_FAIL';

export const USER_LOGGEDIN = 'USER_LOGGEDIN';
export const USER_NOT_LOGGEDIN = 'USER_NOT_LOGGEDIN';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';


export const GET_ERROR_MSG = 'GET_ERROR_MSG';
export const GET_SUCCESS_MSG = 'GET_SUCCESS_MSG';
export const CLEAR_MSG = 'CLEAR_MSG';


// internal
//export const INTUSER_LOGGEDIN = 'INTUSER_LOGGEDIN';
//export const INTUSER_NOT_LOGGEDIN = 'INTUSER_NOT_LOGGEDIN';
//export const INTUSER_LOADING = 'INTUSER_LOADING';
//export const INTUSER_LOADED = 'INTUSER_LOADED';
//export const INTSIGNIN_SUCCESS = 'INTSIGNIN_SUCCESS';
//export const INTSIGNIN_FAIL = 'INTSIGNIN_FAIL';
//export const INTLOGOUT_SUCCESS = 'INTLOGOUT_SUCCESS';
//export const GET_INTSLOTS = 'GET_INTSLOTS';
//export const INTSLOTS_FAIL = 'INTSLOTS_FAIL';
//export const ACTION_FAIL = 'ACTION_FAIL';
//export const ACTION_SUCCESS = 'ACTION_SUCCESS';
